{% set name = "assertpy" %}
{% set version = "0.13" %}
{% set sha256 = "3c288e81e1c5118b9722a1f396db21724916cfb480f3c0c079c4af91ee6f79ce" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: python setup.py install --record record.txt

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - assertpy

about:
  home: https://github.com/ActivisionGameScience/assertpy
  license: BSD 3-Clause
  license_file: LICENSE
  summary: 'Assertion library for python unit testing with a fluent API'
  dev_url: https://github.com/ActivisionGameScience/assertpy

extra:
  recipe-maintainers:
    - dwyatte
    - saturnboy
