{% set name = "assertpy" %}
{% set version = "1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: acc64329934ad71a3221de185517a43af33e373bb44dc05b5a9b174394ef4833
  - url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
    sha256: 81366870bee75cc70e88d46efe52b9577ff9d0cf2c621d179da8405059d8524f
    folder: gh

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

# Cygwin fails the tests: PermissionError: [Errno 13] Permission denied: 'C:\\cygwin64\\tmp\\tmp5yyq74qb'
{% set tests_to_skip = "test_contents_of_path" %}
{% set tests_to_skip = tests_to_skip + " or test_contents_of_path_ascii" %}
{% set tests_to_skip = tests_to_skip + " or test_contents_of_return_type" %}
{% set tests_to_skip = tests_to_skip + " or test_contents_of_return_type_ascii" %}
{% set tests_to_skip = tests_to_skip + " or test_is_child_of_failure" %}

test:
  source_files:
    - gh/tests
  imports:
    - assertpy
  requires:
    - pip
    - pytest
  commands:
    - pip check
    - pytest gh/tests -v  # [not win]
    - pytest gh/tests -v -k "not ({{ tests_to_skip }})"  # [win]

about:
  home: https://github.com/assertpy/assertpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Assertion library for python unit testing with a fluent API
  description: |
    Simple assertions library for unit testing in Python 
    with a nice fluent API. Supports both Python 2 and 3.
  dev_url: https://github.com/assertpy/assertpy
  doc_url: https://github.com/assertpy/assertpy

extra:
  recipe-maintainers:
    - dwyatte
    - saturnboy
