travis:
  secure:
    BINSTAR_TOKEN: fGbVDuCUqBXnUq8DxVhy41ta/FKomjnwZfTgmuZ1dYf3bB8Dxrwzd7FvC2akyRv0WnegQtf/Qo2Ji+W0qquHwEt0GiCqdSD86tC3Je87FSkmdBX0C9m11AAuoPCim4odrBhb9rlw5SN51gDj4veUD++ixnaf333SXrIxTz88fK7OKSX0G9evCnnSrNNRGkgfFOuf09UGRE7y/3AnmKJYkhM1AgcGvFC6ivQqFHtrdmkGaCitj008HenfqAFffrKtorclLIAOJpG/jkwyFkk+zpWWqX4Fen4yG5ooFVFRGzJvG0iDzTCpcvUJrV0IY2HdliMj410FD5t3+w9xkWrhQJZVr0gczfHqTnGvaGOHGSr/GXjb1Ua8AJjjqDAtahRduUSmde7xvJHWlmE7sBMi5xITUzEiRJQdpU1pKqGGGbbFxpoPWnKOZkjpyGObytqbzgI/71MlqEuwqLbraGy1D2rWFQ75H/BCEzNXDzpmd9DzRnOHmsIh/u0Av0Cmqcf7Q1cOm+iZNzSd1C+g0CcASe5SPWbptmaeDgBQ4vSE+PHTn+RUCCwOO8rbWLsBPDQWgHbmYWmUkxT+BPLCkXgtWFxNRtPwmHCiMT1qxWnW/8aNhn4xrPH0cPZeUNICnnZLOeLw3gf0kyOSBciFNdNq+W6eN7/MN/QgeinHve6aRQ4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
