travis:
  secure:
    BINSTAR_TOKEN: W0sbfZdtH5F63fdKWNcorXB3tNnqQLmYZ4ziAg8XMGdAG3rhUmxkOGwdsnJnMZRCBunmBbfgPUkrdgUfJjg1o3CCeW0YkhysON2dyquEVpV0mtD6TcyxQ8cdoAtU00Zj6vINInvFQkFSrtOidB0et/BGj+MZvr8jAr+rgqonFBFIyKin42l32R39vCwMg9AFjFAhpFx2ytN9cFlRBxo/EKAe7xib7K4DPd09RuMmAw2do2ywKQ6g9JwlIv/gpvP/DzfrfAl11mP6PnJoic/9HORCShP9FanrcDMtzc5W8v3Aa4aS2I/aKJCA2R2i3e1cIr6VaQX2xR8SnH6aqs0gvMx0A4V/JvxmHomwce0h9jdo5tYvZZi2BTmSkAhGJI8dMDju10+km+VFPusG7gFrB1K3Pvtl7Fwz7aO/L3cv6FLVl1oypj6P9oksCUQQsfDDXnIe5zlrCfew/AI4l2QepWEYWWKjCxzy891AOmLlLHCMAgGHuWyaZG5d6WWkrRGYyknYm79jSMZrb8Vd/WoNgyoLKbyMTb+V6Yk89COP2RyN5QuXHm3iSVu8Q8/1pjQC6VC08SUexmAhKM9Ed+95hyxubyHA1lHo0zWhSyiNxQVH88nRIzuZoeg1F8k/luRSGvbJuiR/hvUrIShQgUhmEg9RQkRHcQc6z0jRcunT/vo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
