travis:
  secure:
    BINSTAR_TOKEN: VuEf7VPLLt9VVIhNRLVd2HmU8GJXorp5aUyL6vaf6Ribux5Zj1MGzVs5Q6KIRWjy2ki08hzZDjri+RMvIcm4u+/rZujhhhNNo2efiocgzy/27HLVcXxXtz+H/N2zrXpsegol4+oKWrWHLhW+kEoei3f5ybY6nsa7/Fh9xX/kd46EYZJG5f45ZehEn8SGPGZ+KUHSWHleMLdOe0RFK1Zy3xRRa3jkIyc5IzUFWVbvWRoP0K5olwfCdSfHVk68OuJOGOFhdn/LWZ02ailz6gYD78F6IWp312ubLrFMqbKUTzWFjjFX0n7kOncU/bLWv4rdAPOc71tvGdoKSya2ytWQViCSF1gmf80FbQZhZZrjw/5/5sjTFDupQMmls8K2c7SPEp48yO41ctTE/nqvxGzb2iSxqwqfaIZRVztChH9UEc0I/cU/ibCPLGzAojh2HLfCF6fnRCtmV2ec1WkAyUscbjrY0olvUzqAK/YeqQ18fP5YhUCD08ULZMPv17gnWhe2z0vQLlNS2XoI0wfcvYz3rZ1cHi8rGGV8uE2Fvy3tKK/ODqwW96uJJXNhlnspplI6DpJeWl6dMsNePReLcB2TMFpM6tHEOSkbE8m4WfdzOZYVEG4yeEfqQQdFFPk6Joo19nNycwx0iCqKvLkPH2raEyfQrCyvdjrZtW+DK+cO1hc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
